version: "3.8"

services:
  servico-lancamento-fatura:
    container_name: servico-lancamento-fatura
    image: 442494/poc-quarkus-native-reactive-bd:v1.0.0
    environment:
      - QUARKUS_PORT=$QUARKUS_PORT
      - QUARKUS_HTTP_CORS=$QUARKUS_HTTP_CORS

      - QUARKUS_DATASOURCE_DB_KIND=${QUARKUS_DATASOURCE_DB_KIND}
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
      - QUARKUS_DATASOURCE_VERTX_URL=${QUARKUS_DATASOURCE_VERTX_URL}
    ports:
      - $QUARKUS_PORT:$QUARKUS_PORT
    networks:
      - "host_sendbox"
     

networks:
  host_sendbox:
    external: true